language: groovy
jdk:
- openjdk7
sudo: false
before_install:
- export TZ=Europe/Stockholm
- date
- rm -rf ~/.sdkman
- curl -s http://get.sdkman.io | bash
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- sdk install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails
- wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
deploy:
  provider: releases
  api_key:
    secure: WzjUkHWU2RSNGEigti9C2i3ok3p+6dMXrYto8NuDahdoQ1QHli1ISr02wadTxBtfWNh4avL9KNF108R4i7ECNHdr/koYhWVSC1NReb/DtdrHkupJRKwVEnovaPsAL/YKn1/Ntfc5PcddTpGbRDtm3dY9pVfG+NHpqonthQ5xclKRXZXfZcVyA2w15PD3A0AdCCuK6ESiYU1MxuZNA8qRGSsoYxx3ouaaRwf2amecAnVxlw1wFuH0YSkBpGKnGyUyvoQ0dfhrc+By6ppMbIy5yq7GN8X5NnKVqnOR2rorWcjAsdBP/aaKZSk+WAqikunw+F2G9MdHYCkP6KXpkP9fIymbaF5Z1Qma2EeaXULNhHyXqm4RlF3xRQOXGOo9Nr40ipa6qrXA5whFn+Mn6qpbYE3EggsJkL6IQhtWd+kt6WQWFGDCNRm8TQ8D52gVK1g9gpS3gcMsJOk5PMO2WYXqIz1p+ZiinhOWwD8wxFMYFsyRYmYuGR8ZERjfYyM1KwMSQzZt8aqPDJ3Ifzppijju7npI2EBnyBhfetLdH0U3QlYcQPu9lxXJsP5H2C/ySkeVWQb0YGvEKxAXFKCHOGogn9/owMXIvtCBP5YiOrfstgoNEGL+YccPdgOLM9k5KFZpjupZfWYzzGmHrcz2tI9GK+BB1p0GKNY6SZ7+Pb//YZs=
  file_glob: true
  file: "target/ala-hub-*.war"
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/ala-hub
    all-branches: true
    tags: true